DROP DATABASE IF EXISTS users_db;
CREATE DATABASE users_db;

USE users_db;

CREATE TABLE users (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	username VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    date_added DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);